config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session_path
  end

  root to: "items#index"

  resources :items do
    resources :comments
  end

  resources :items do
    resources :likes
  end

  resources :users do 
    member do 
      get :following, :followers
    end 
  end 

  resources :relationships, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
   belongs_to :item
   belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :item
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, :omniauth_providers => [:facebook]

  has_many :items
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", 
                                  foreign_key: "followed_id", 
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :user_name, presence: true, length: {minimum: 4, maximum: 16}

  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end 

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end 

  def following?(other_user)
    following.include?(other_user)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
	 	 devise_parameter_sanitizer.for(:sign_up) << :user_name
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @item.comments.build(comment_params)
    if @comment.save
      flash[:success] = "You commented the hell out of that post!"
      redirect_to :back
    else
      flash[:alert] = "Check the comment form, something went horribly wrong."
      render root_path
    end
  end

  def destroy
    @comment = @item.comments.find(params[:id])
    @comment.destroy
    flash[:success] = "Comment deleted :("
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:thoughts)
  end

  def set_post
    @item = Item.find(params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
  	@item = Item.new
  end

  def create
  	Item.create(item_params)
  	redirect_to items_path
  end

  def item_params
  	params.require(:item).permit(:image, :description, :store, :category, :price, :rating)
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @item.likes.create
    render json: {new_like_count: @item.likes.count}
  end
end

app/controllers/registration_controller.rb
class RegistrationsController < Devise::RegistrationsControlle
	private 

	def sign_up_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
	end 

	def account_update_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
	end 
end 

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :logged_in_user

	def create
		user = User.find(params[:followed_id])
		current_user.follow(@user)
		respond_to do |format|
			format.html { redirect_to @user}
			format.js
		end 
		redirect_to user
	end 

	def destroy
		user = Relationship.find(params[:id]).followed
		current_user.unfollow(@user)
		respond_to do |format|
			format.html {redirect_to @user}
			format.js
		end 
		redirect_to user
	end 

	def logged_in_user
    unless user_signed_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end



class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:following, :followers]

	def show
		@user = User.find(params[:id])
	end

	def index 
		@users = User.all 
	end

	def logged_in_user
    unless user_signed_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

	def following 
		@title = "Following"
		@user  = User.find(params[:id])
		@users = @user.following.paginate(page: params[:page])
		render 'show_follow'
	end 

	def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_for [@item , @comment] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.submit 'Leave Comment' %>
<% end %>

app/views/items/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"></link>
    <title>Photos</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <% if @items.any? %>
      <% @items.each do |item| %>
        <%= image_tag item.image.url(:medium) %>
        <div class="time-ago">
          <%= time_ago_in_words item.created_at %>
        </div>

        <h2><%= item.description %></h2>
        <h4><%= item.store %></h4>
        <h4><%= item.category %></h4>
        <% if item.price === nil %>
          no price
        <% else %>
          <h5> £<%= sprintf '%.2f', item.price %></h5>
        <% end %>
        <% if user_signed_in? %>
          <div>
            <%= link_to "Like", item_likes_path(item), class: 'likes-link' %>
            <span class="likes_count">
              <%= item.likes.count %>
            </span>
            <span class="likes_pluralisation">
              <%= 'like'.pluralize(item.likes.count) %>
            </span>
          </div>
        <% end %>
        <p><%= item.rating %>/5</p>
        <% if item.comments.any? %>
        <% item.comments.each do |comment| %>
          <p><%= comment.thoughts %></p>
        <% end %>
      <% end %> 
        <%= form_for [item, item.comments.new] do |f| %>
           <%= f.text_field :thoughts, placeholder: 'Add a comment...' %>
           <%= f.submit 'Leave Comment' %>
         <% end %>
      <% end %>
    <% else %>
      <p>No items yet</p>
    <% end %>
		<%= link_to "Add an item", new_item_path %>
    </body>
</html>

app/views/items/new.html.erb
<%= form_for @item, html: {multipart: true} do |f| %>
  <%= f.file_field :image %>
	<%= f.label :description %>
	<%= f.text_field :description, :required => true %>
	<%= f.label :store %>
	<%= f.select :store,['Zara', 'H&M', 'Topshop'], :required => true %>
	<%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.label :category %>
  <%= f.select :category,['Jackets and Coats', 'Dresses', 'Shoes'], :required => true %>
	<%= f.label :price %>
	<%= f.number_field :price %>
	<%= f.submit "Add item" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Boris</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
  <body>
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
  <% end %>
    <%= yield %>

  </body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("followers").html('<% @user.followers.count %>')

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
<div>
	<%= hidden_field_tag :followed_id, @user.id %>
</div>
<%= f.submit "Follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user === @user %>
	<% if current_user.following?(@user) %>
		<%= render 'unfollow' %>
	<% else %>
		<%= render 'follow' %>
	<% end %>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<a href="<%= following_user_path(@user) %>">
	<strong>
		<%= @user.following.count %>
	</strong>
		following
</a>
<a href="<%= followers_user_path(@user) %>">
	<strong>
		<%= @user.followers.count %>
	</strong>
	followers
</a>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), 
							html: {method: :delete},
							remote: true) do |f| %>
	<%= f.submit "Unfollow" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.user_name, user %> 
</li>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<%= link_to user.user_name, user %>
	<%= user.email %>
<% end %>

app/views/users/show.html.erb
<%= @user.user_name %>
<%= render 'stats' %>
<%= render 'follow_form' if user_signed_in? %>

app/views/users/show_follow.html.erb
<h1><%= @user.user_name %></h1>
  <span><%= link_to "view my profile", @user %></span>
<%= render 'stats' %>
<h3><%= @title %></h3>
  <% if @users.any? %>
    <ul>
      	<%= render @users %>
    </ul>
  <% end %>
  